polish the ui
kimitaWanjohi/bookstore pull request #6
Opened 2023-05-12 17:50 UTC by kimitaWanjohi

2023-05-12 18:23 UTC, AmaduKamara requested changes
# Status: Required Changes ♻️ ♻️ ♻️

Hi @kimitaWanjohi,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✅ You used Gitflow correctly 👍🏽
✅ The Linter checks passed 👍🏽

## Required Changes ♻️
_Check the comments under the review._

- [ ] Kindly style your app to match the original design as required 👍🏽
- [ ] I also noticed that, when I navigate from one page to another, the books get duplicated as many times as I navigate. Kindly fix that 👍🏽

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-05-12 18:23 UTC, AmaduKamara commented on src/components/Book.jsx
>        </button>
- [ ] Let's try to stick to the project requirements as this is setting us up for real world projects in the future when we get a real job. Kindly style your app to have all sections and placeholders even if they're not doing anything in the app at the moment but for project guideline and requirement, let's work according to how we're required to style the app. 👍🏽
- [ ] Currently your app does not mact the original design given, hence, you are to match the original design in order for your project to be complete. Please work on it 👍🏽

**Your App**

<img width="1642" alt="Screenshot 2023-05-12 at 6 13 31 PM" src="https://github.com/kimitaWanjohi/bookstore/assets/50941074/39be183b-676b-4c4e-98ee-50f2312f356e">

**The Original Design**

<img width="1031" alt="Screenshot 2023-05-12 at 6 11 24 PM" src="https://github.com/kimitaWanjohi/bookstore/assets/50941074/13dc08f1-f74a-4ad4-bc18-1a01670c8e65">

2023-05-12 21:20 UTC, MeqdamAlqudah requested changes
Hi @kimitaWanjohi , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![image](https://github.com/kimitaWanjohi/bookstore/assets/74744787/71464031-c0d6-4807-a831-36b5c921abcf)

 ## Highlights
:+1: colors 
:+1: project functionality 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-12 21:20 UTC, MeqdamAlqudah commented on src/components/Navbar.jsx
>  import { useNavigate } from "react-router-dom";
- [ ] Please as the last reviewer said you should work on your code and make it match the design currently these are the things that are missing in your design : 
- the navigation it doen't match the design the background should be white and the height should look as in the design  
- the chapter name and the button should match the design , your code 
![image](https://github.com/kimitaWanjohi/bookstore/assets/74744787/5b5d1759-f1d4-45fb-a0f2-ad7f22ea398e)
 the design 
![image](https://github.com/kimitaWanjohi/bookstore/assets/74744787/533af3fa-4e11-4498-ad97-bdf5987a910c)
- there is a line between the chapter info and the progress bar ]
- the distance between the chapter  info and the progress bar should match the design 
![image](https://github.com/kimitaWanjohi/bookstore/assets/74744787/6633502b-f2e6-4922-9ba2-f4d5b52e98b2)
- the border of the input field shoudl match the design and the text inside it color should match the design 
![image](https://github.com/kimitaWanjohi/bookstore/assets/74744787/bcf89010-7aec-41be-b997-edf76c057a98)
- the background of the card section should match the design 
![image](https://github.com/kimitaWanjohi/bookstore/assets/74744787/45220fad-770b-4f1b-874d-e841d6e99b2b)

- the distance between each book card should match the design 
![image](https://github.com/kimitaWanjohi/bookstore/assets/74744787/84928757-2278-48bf-8340-9d06a935812d)

2023-05-13 08:17 UTC, frank1738 approved these changes
Hi @kimitaWanjohi , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media2.giphy.com/media/tIeCLkB8geYtW/giphy.gif"/>

## Highlights

✅ Correct use of Gitflow
✅ No linter error
✅ App is designed as expected 👍 



## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-13 09:50 UTC, merged